vikings_bot_2/planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

vikings_bot_2/global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: "map"
      map_topic: "/vikings_bot_2/map"
      #transform_tolerance: 0.5
      robot_base_frame: vikings_bot_2/base_link
      # use_sim_time: True
      #robot_radius: 0.175
      footprint: "[[0.8, 0.45], [-0.3, 0.45], [-0.3, -0.45], [0.8, -0.45]]"
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", rm_safe_objects_layer, "inflation_layer"]
      rm_safe_objects_layer:
        plugin: "vikings_bot_point_cloud_processor/RmSafeObstaclesLayer"
        enabled: True
        point_topic: "/vikings_bot_2/safe_obstacle_points"
        inflation_radius: 7 #px
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        # publish_voxel_map: False
        # origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        #observation_sources: scan # SET FROM LAUNCH FILE
        scan:
          topic: /vikings_bot_2/lidar_scan
          #sensor_frame: vikings_bot_2/lidar_link
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 6.0
          raytrace_min_range: 0.0
          obstacle_max_range: 5.5
          obstacle_min_range: 0.0
        point_cloud:
          topic: /vikings_bot_2/camera/depth/color/points
          max_obstacle_height: 2.0
          min_obstacle_height: 0.05 # otherwise floor is detected as obstacle
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 4.0
        inflation_radius: 0.65
      always_send_full_costmap: True